services:
  backend:
    build:
      context: ./backend
    network_mode: host
    container_name: rfid-backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - backend/.env

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: rfid-proxy
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "9090:9090"
    depends_on:
      - backend
    env_file:
      - proxy/.env
    networks:
      - rfid-net

networks:
  rfid-net:
    driver: bridge
