services:
  rfid:
    build:
      context: ./backend
    container_name: rfid-backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - backend/.env
    expose:
      - 8001
    networks:
      - rfid-net

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: rfid-proxy
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - rfid
    env_file:
      - proxy/.env
    expose:
      - 9090
    networks:
      - rfid-net

networks:
  rfid-net:
    driver: bridge
