# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'fastapi',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.websockets',
        'flask',
        'flask_sock',
        'flask_cors',
        'simple_websocket',
        'gunicorn',
        'fnctl',
        'sqlalchemy',
        'psycopg2',
        'cryptography',
        'jwt',
        'bcrypt',
        'dotenv',
        'pydantic',
        'pysqlite2',
        'multipart',
        'mx.DateTime',
        'MySQLdb',
        'requests',
        'dateutil',
        'httpx',
        'tzdata',
        'pandas',
        'pandas._libs',
        'pandas._libs.tslibs',
        'pandas._libs.tslibs.timestamps',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.interval',
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.styles',
        'docx',
        'docx.opc',
        'docx.opc.part',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='rfid-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='rfid-backend',
)
